name: CI/CD Pipeline

on:
  push:
    branches: [master]

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
    # Step untuk checkout repository
    - name: Checkout repository
      uses: actions/checkout@v2

    # Step untuk deploy ke VPS
    - name: Deploy to VPS
      uses: appleboy/ssh-action@v0.1.3  # Gunakan versi yang lebih stabil
      with:
        host: ${{ secrets.HOST }}
        username: ${{ secrets.USERNAME }}
        key: ${{ secrets.SSH_PRIVATE_KEY }}
        port: 64000
        script: |
          # Buat direktori cicd dan direktori untuk proyek jika belum ada
          if [ ! -d "/var/www/html/cicd" ]; then
            mkdir -p /var/www/html/cicd
          fi

          if [ ! -d "/var/www/html/cicd/2305083" ]; then
            mkdir -p /var/www/html/cicd/2305083
          fi

          # Masuk ke dalam direktori proyek
          cd /var/www/html/cicd/2305083

          # Jika sudah ada repositori Git, lakukan git pull, jika belum ada lakukan git clone
          if [ ! -d ".git" ]; then
            git clone https://github.com/rexxus166/Praktikum-Git.git .
          else
            git pull origin main
          fi

          # Memberikan hak akses yang sesuai
          chmod -R 755 /var/www/html/cicd/2305083